# Generated by Django 4.2.13 on 2024-06-27 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title if the book', max_length=50)),
                ('publication_date', models.DateField(verbose_name='Date of book publication')),
                ('isbn', models.CharField(max_length=20, verbose_name='isbn number of the book')),
            ],
        ),
        migrations.CreateModel(
            name='Conributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Conributor first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Conributor last name')),
                ('email', models.EmailField(help_text='The Conributor email with the contributor.', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='The Review Text', max_length=254)),
                ('rating', models.IntegerField(help_text='rating of reviewer has given')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date the review has created')),
                ('date_updated', models.DateTimeField(help_text='date of last review edite', null=True)),
                ('book', models.ForeignKey(help_text='The book thst this review for', on_delete=django.db.models.deletion.CASCADE, to='reviews.book')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookConributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('AUTHOR', 'Author'), ('CO_AUTHOR', 'Co_Author'), ('EDITOR', 'Editor')], max_length=20, verbose_name='role of contributor for this book')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.book')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.conributor')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='contributors',
            field=models.ManyToManyField(through='reviews.BookConributor', to='reviews.conributor'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.publisher'),
        ),
    ]
